<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

	<ItemGroup>
    <None Remove="Fonts\Tablon-Regular.ttf" />
    <None Remove="Windows\WindowsImages\20.png" />
    <None Remove="Windows\WindowsImages\DoubleMouseButton.png" />
    <None Remove="Windows\WindowsImages\LeftMouseButton.png" />
    <None Remove="Windows\WindowsImages\LicenseIco.png" />
    <None Remove="Windows\WindowsImages\Loading.gif" />
    <None Remove="Windows\WindowsImages\Logo01.png" />
    <None Remove="Windows\WindowsImages\Logo02.png" />
    <None Remove="Windows\WindowsImages\Logo03.png" />
    <None Remove="Windows\WindowsImages\LogoDC.png" />
    <None Remove="Windows\WindowsImages\RightMouseButton.png" />
    <None Remove="Windows\WindowsImages\Search.png" />
    <None Remove="Windows\WindowsImages\Settings.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Tablon-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Windows\WindowsImages\DoubleMouseButton.png" />
    <Resource Include="Windows\WindowsImages\LeftMouseButton.png" />
    <Resource Include="Windows\WindowsImages\LicenseIco.png" />
    <Resource Include="Windows\WindowsImages\Loading.gif" />
    <Resource Include="Windows\WindowsImages\Logo01.png" />
    <Resource Include="Windows\WindowsImages\Logo03.png" />
    <Resource Include="Windows\WindowsImages\20.png" />
    <Resource Include="Windows\WindowsImages\Logo02.png" />
    <Resource Include="Windows\WindowsImages\LogoDC.png" />
    <Resource Include="Windows\WindowsImages\RightMouseButton.png" />
    <Resource Include="Windows\WindowsImages\Search.png" />
    <Resource Include="Windows\WindowsImages\Settings.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Windows\Pages\Settings\" />
  </ItemGroup>

</Project>
