<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Windows\Pages\MainWindow\**" />
    <Compile Remove="Windows\Pages\Settings\**" />
    <EmbeddedResource Remove="Windows\Pages\MainWindow\**" />
    <EmbeddedResource Remove="Windows\Pages\Settings\**" />
    <None Remove="Windows\Pages\MainWindow\**" />
    <None Remove="Windows\Pages\Settings\**" />
    <Page Remove="Windows\Pages\MainWindow\**" />
    <Page Remove="Windows\Pages\Settings\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Fonts\Aventura.ttf" />
    <None Remove="Fonts\Bree CYR var Regular.ttf" />
    <None Remove="Fonts\Brenzo Slab Personal Use.otf" />
    <None Remove="Fonts\Domino Regular.otf" />
    <None Remove="Fonts\MOSCOW2024.otf" />
    <None Remove="Fonts\Pecita.otf" />
    <None Remove="Fonts\pizza hut.otf" />
    <None Remove="Fonts\sangha.ttf" />
    <None Remove="Windows\WindowsImages\Logo04.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Aventura.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Bree CYR var Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Brenzo Slab Personal Use.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Monocraft.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\MOSCOW2024.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Pecita.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\sangha.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Tablon-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Windows\WindowsImages\ArrowFrameComponent.png" />
    <Resource Include="Windows\WindowsImages\DoubleMouseButton.png" />
    <Resource Include="Windows\WindowsImages\Labels\Command.png" />
    <Resource Include="Windows\WindowsImages\Labels\File.png" />
    <Resource Include="Windows\WindowsImages\Labels\Folder.png" />
    <Resource Include="Windows\WindowsImages\Labels\Link.png" />
    <Resource Include="Windows\WindowsImages\LeftMouseButton.png" />
    <Resource Include="Windows\WindowsImages\LicenseIco.png" />
    <Resource Include="Windows\WindowsImages\Loading.gif" />
    <Resource Include="Windows\WindowsImages\Logo01.png" />
    <Resource Include="Windows\WindowsImages\Logo03.png" />
    <Resource Include="Windows\WindowsImages\20.png" />
    <Resource Include="Windows\WindowsImages\Logo02.png" />
    <Resource Include="Windows\WindowsImages\Logo04.png" />
    <Resource Include="Windows\WindowsImages\LogoDC.png" />
    <Resource Include="Windows\WindowsImages\RightMouseButton.png" />
    <Resource Include="Windows\WindowsImages\Search.png" />
    <Resource Include="Windows\WindowsImages\Settings.png" />
    <Resource Include="Windows\WindowsImages\Wifi.png" />
    <Resource Include="Windows\WindowsImages\WifiOff.png" />
    <Resource Include="Windows\WindowsImages\WifiOn.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CounterScrollBar\DataScroll.csproj" />
    <ProjectReference Include="..\IEL\IEL.csproj" />
    <ProjectReference Include="..\InterpreterCommand\InterpreterCommand.csproj" />
  </ItemGroup>

</Project>
