<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <WV2WinRTWrapWebViewTypes>False</WV2WinRTWrapWebViewTypes>
    <Configurations>Debug;Release;Testing</Configurations>
    <WebView2LoaderPreference>Dynamic</WebView2LoaderPreference>
    <WV2WinRTVerbosity>high</WV2WinRTVerbosity>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <StartupObject></StartupObject>
    <UseWindowsForms>True</UseWindowsForms>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
	<PropertyGroup>
		<GeckoDriverPlatform>win32</GeckoDriverPlatform>
	</PropertyGroup>

  <ItemGroup>
    <None Remove="CORE\Audio\Move.mp3" />
    <None Remove="CORE\Audio\Notification.mp3" />
    <None Remove="CORE\Audio\Pop-Up.mp3" />
    <None Remove="Fonts\Bree CYR var.ttf" />
    <None Remove="Fonts\Brenzo Slab Personal Use.otf" />
    <None Remove="Fonts\Deledda Open Regular.ttf" />
    <None Remove="Fonts\Monocraft.otf" />
    <None Remove="Fonts\MOSCOW2024.otf" />
    <None Remove="Fonts\October Pro Blk.ttf" />
    <None Remove="Fonts\Pecita.otf" />
    <None Remove="Fonts\Plup.ttf" />
    <None Remove="Fonts\RussianRail G Pro.otf" />
    <None Remove="Fonts\sangha.ttf" />
    <None Remove="Fonts\Tablon.ttf" />
    <None Remove="Fonts\Vollda.otf" />
    <None Remove="UI\Images\Arrow.png" />
    <None Remove="UI\Images\BrowserChangeSystem.png" />
    <None Remove="UI\Images\Check.png" />
    <None Remove="UI\Images\Cross.png" />
    <None Remove="UI\Images\DoubleMouseButton.png" />
    <None Remove="UI\Images\IconMainApplication.png" />
    <None Remove="UI\Images\IconMainGray.png" />
    <None Remove="UI\Images\IconMainSettings.png" />
    <None Remove="UI\Images\Labels\Folder.png" />
    <None Remove="UI\Images\LeftMouseButton.png" />
    <None Remove="UI\Images\LightBulb.png" />
    <None Remove="UI\Images\Loading.wmv" />
    <None Remove="UI\Images\Media\Happy.mp4" />
    <None Remove="UI\Images\Media\Loading\LoadingDefault.mp4" />
    <None Remove="UI\Images\Menu.png" />
    <None Remove="UI\Images\NotMouseButton.png" />
    <None Remove="UI\Images\Plus.png" />
    <None Remove="UI\Images\Reload.png" />
    <None Remove="UI\Images\RightMouseButton.png" />
    <None Remove="UI\Images\Search.png" />
    <None Remove="UI\Images\Sorting\Sorting-NameAZ.png" />
    <None Remove="UI\Images\Sorting\Sorting-NameZA.png" />
    <None Remove="UI\Images\Sorting\Sorting-Not.png" />
    <None Remove="UI\Images\Sorting\Sorting-Tag.png" />
    <None Remove="UI\Images\Tag.png" />
    <None Remove="UI\Images\ValidKeyIcon.png" />
    <None Remove="UI\Images\Volume.png" />
    <None Remove="UI\Images\Warning.png" />
    <None Remove="UI\Images\Wifi.png" />
    <None Remove="UI\Images\WifiOff.png" />
    <None Remove="UI\Images\WifiOn.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="CORE\Resources\PaletteDictionary.xaml" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="MMC20">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>8e80422b-cac4-472b-b272-9635f1dfef3b</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3595.46" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Selenium.WebDriver.MicrosoftDriver" Version="17.17134.0" />
    <PackageReference Include="System.Management" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IEL\IEL.csproj" />
    <ProjectReference Include="..\..\InterpreterCommand\InterpreterCommand.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LibraryPackKey">
      <HintPath>..\..\PackKey\LibraryPackKey\bin\Debug\net8.0\LibraryPackKey.dll</HintPath>
    </Reference>
  </ItemGroup>
	
  <ItemGroup>
    <Resource Include="CORE\Audio\Move.mp3" />
    <Resource Include="CORE\Audio\Notification.mp3" />
    <Resource Include="CORE\Audio\Pop-Up.mp3" />
    <Resource Include="CORE\Resources\PaletteDictionary.xaml" />
    <Resource Include="Fonts\Bree CYR var.ttf" />
    <Resource Include="Fonts\Brenzo Slab Personal Use.otf" />
    <Resource Include="Fonts\Deledda Open Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Monocraft.otf" />
    <Resource Include="Fonts\MOSCOW2024.otf" />
    <Resource Include="Fonts\October Pro Blk.ttf" />
    <Resource Include="Fonts\Pecita.otf" />
    <Resource Include="Fonts\Plup.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RussianRail G Pro.otf" />
    <Resource Include="Fonts\sangha.ttf" />
    <Resource Include="Fonts\Tablon.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Vollda.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Arrow.png" />
    <Resource Include="UI\Images\Autor\MINSI.jpg" />
    <Resource Include="UI\Images\Autor\VECTOR.jpg" />
    <Resource Include="UI\Images\BrowserChangeSystem.png" />
    <Resource Include="UI\Images\Check.png" />
    <Resource Include="UI\Images\Cross.png" />
    <Resource Include="UI\Images\DoubleMouseButton.png" />
    <Resource Include="UI\Images\IconMainApplication.png" />
    <Resource Include="UI\Images\IconMainGray.png" />
    <Resource Include="UI\Images\IconMainSettings.png" />
    <Resource Include="UI\Images\Labels\Folder.png" />
    <Resource Include="UI\Images\LeftMouseButton.png" />
    <Resource Include="UI\Images\LightBulb.png" />
    <Resource Include="UI\Images\Media\Happy.mp4" />
    <Resource Include="UI\Images\Media\Loading\LoadingDefault.mp4" />
    <Resource Include="UI\Images\Menu.png" />
    <Resource Include="UI\Images\NotMouseButton.png" />
    <Resource Include="UI\Images\Plus.png" />
    <Resource Include="UI\Images\Reload.png" />
    <Resource Include="UI\Images\RightMouseButton.png" />
    <Resource Include="UI\Images\Search.png" />
    <Resource Include="UI\Images\Sorting\Sorting-NameAZ.png" />
    <Resource Include="UI\Images\Sorting\Sorting-NameZA.png" />
    <Resource Include="UI\Images\Sorting\Sorting-Not.png" />
    <Resource Include="UI\Images\Sorting\Sorting-Tag.png" />
    <Resource Include="UI\Images\Tag.png" />
    <Resource Include="UI\Images\ValidKeyIcon.png" />
    <Resource Include="UI\Images\Volume.png" />
    <Resource Include="UI\Images\Warning.png" />
    <Resource Include="UI\Images\Wifi.png" />
    <Resource Include="UI\Images\WifiOff.png" />
    <Resource Include="UI\Images\WifiOn.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Resource Update="Fonts\Aventura.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\barboskinsakzident.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\Bree CYR var.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\Brenzo Slab Personal Use.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\ChakraPetch-Regular.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\CureEater-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\Monocraft.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\MOSCOW2024.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\Pecita.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\RussianRail G Pro.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\sangha.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\Tablon-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\Vollda-Bold.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Update="Fonts\zhuan_FuturaNowScript-Rg.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
