<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <WebView2UseWinRT>True</WebView2UseWinRT>
    <WebView2EnableCsWinRTProjection>True</WebView2EnableCsWinRTProjection>
    <Platforms>AnyCPU;x64;x86</Platforms>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>True</UseWPF>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\3PIX.ttf" />
    <None Remove="Fonts\Alphasano.ttf" />
    <None Remove="Fonts\Bree CYR var.ttf" />
    <None Remove="Fonts\Brenzo Slab Personal Use.otf" />
    <None Remove="Fonts\Deledda Open Regular.ttf" />
    <None Remove="Fonts\Monocraft.otf" />
    <None Remove="Fonts\MOSCOW2024.otf" />
    <None Remove="Fonts\October Pro Blk.ttf" />
    <None Remove="Fonts\Pecita.otf" />
    <None Remove="Fonts\Play.ttf" />
    <None Remove="Fonts\Plup.ttf" />
    <None Remove="Fonts\RussianRail G Pro.otf" />
    <None Remove="Fonts\Sangha.ttf" />
    <None Remove="Fonts\Tablon.ttf" />
    <None Remove="Fonts\Vollda.otf" />
    <None Remove="UI\Images\Home.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="CORE\Resources\PaletteDictionary.xaml" />
    <Page Remove="CORE\Resources\VisualDictionary.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\3PIX.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Alphasano.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Bree CYR var.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Brenzo Slab Personal Use.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Deledda Open Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Monocraft.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\MOSCOW2024.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\October Pro Blk.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Pecita.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Play.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Plup.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RussianRail G Pro.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Sangha.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Tablon.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Vollda.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.Common" Version="146.0.70" />
    <PackageReference Include="CefSharp.H.264" Version="79.1.360.1" />
    <PackageReference Include="CefSharp.Wpf.NETCore" Version="146.0.70" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.3" />
    <PackageReference Include="System.Management" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IEL\LibraryIEL\LibraryIEL.csproj" />
    <ProjectReference Include="..\..\InterpreterCommand\Interpreter\Interpreter.csproj" />
    <ProjectReference Include="..\OIEL\OIEL.csproj" />
    <ProjectReference Include="..\OPLAnimation\OPLAnimation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LibraryPackKey">
      <HintPath>..\..\PackKey\LibraryPackKey\bin\Debug\net8.0\LibraryPackKey.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="CORE\Resources\PaletteDictionary.xaml" />
    <Resource Include="CORE\Resources\VisualDictionary.xaml" />
    <Resource Include="UI\Images\Home.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
