<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UI\Pages\MainWindow\**" />
    <EmbeddedResource Remove="UI\Pages\MainWindow\**" />
    <None Remove="UI\Pages\MainWindow\**" />
    <Page Remove="UI\Pages\MainWindow\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Fonts\Aventura.ttf" />
    <None Remove="Fonts\Bree CYR var Regular.ttf" />
    <None Remove="Fonts\Brenzo Slab Personal Use.otf" />
    <None Remove="Fonts\Domino Regular.otf" />
    <None Remove="Fonts\MOSCOW2024.otf" />
    <None Remove="Fonts\Pecita.otf" />
    <None Remove="Fonts\pizza hut.otf" />
    <None Remove="Fonts\RussianRail G Pro.otf" />
    <None Remove="Fonts\sangha.ttf" />
    <None Remove="Fonts\Vollda-Bold.otf" />
    <None Remove="Fonts\zhuan_FuturaNowScript-Rg.ttf" />
    <None Remove="UI\Images\Arrow.png" />
    <None Remove="UI\Images\LightBulb.png" />
    <None Remove="UI\Images\Logo04.png" />
    <None Remove="UI\Images\Plus.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.1.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Aventura.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Bree CYR var Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Brenzo Slab Personal Use.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Monocraft.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\MOSCOW2024.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Pecita.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RussianRail G Pro.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\sangha.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Tablon-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Vollda-Bold.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\zhuan_FuturaNowScript-Rg.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UI\Images\Arrow.png" />
    <Resource Include="UI\Images\DoubleMouseButton.png" />
    <Resource Include="UI\Images\Labels\Command.png" />
    <Resource Include="UI\Images\Labels\File.png" />
    <Resource Include="UI\Images\Labels\Folder.png" />
    <Resource Include="UI\Images\Labels\Link.png" />
    <Resource Include="UI\Images\LeftMouseButton.png" />
    <Resource Include="UI\Images\LicenseIco.png" />
    <Resource Include="UI\Images\LightBulb.png" />
    <Resource Include="UI\Images\Loading.gif" />
    <Resource Include="UI\Images\Logo01.png" />
    <Resource Include="UI\Images\Logo03.png" />
    <Resource Include="UI\Images\20.png" />
    <Resource Include="UI\Images\Logo02.png" />
    <Resource Include="UI\Images\Logo04.png" />
    <Resource Include="UI\Images\LogoDC.png" />
    <Resource Include="UI\Images\Plus.png" />
    <Resource Include="UI\Images\RightMouseButton.png" />
    <Resource Include="UI\Images\Search.png" />
    <Resource Include="UI\Images\Settings.png" />
    <Resource Include="UI\Images\Wifi.png" />
    <Resource Include="UI\Images\WifiOff.png" />
    <Resource Include="UI\Images\WifiOn.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataScroll\DataScroll.csproj" />
    <ProjectReference Include="..\IEL\IEL.csproj" />
    <ProjectReference Include="..\InterpreterCommand\InterpreterCommand.csproj" />
  </ItemGroup>

</Project>
